import { exec } from 'child_process'
import { Item, Provider } from '@shared/types'
import { Icons } from '@shared/icons'

const SYSTEM_ACTIONS: Item[] = [
    {
        id: 'sys:shutdown',
        name: 'Shut Down',
        icon: Icons.system,
        moduleId: 'system',
        metadata: { cmd: 'shutdown /s /t 0' },
        triggers: ['execute'],
    },
    {
        id: 'sys:restart',
        name: 'Restart',
        icon: Icons.system,
        moduleId: 'system',
        metadata: { cmd: 'shutdown /r /t 0' },
        triggers: ['execute'],
    },
    {
        id: 'sys:sleep',
        name: 'Sleep',
        icon: Icons.system,
        moduleId: 'system',
        metadata: { cmd: 'rundll32.exe powrprof.dll,SetSuspendState 0,1,0' },
        triggers: ['execute'],
    },
    {
        id: 'sys:lock',
        name: 'Lock',
        icon: Icons.system,
        moduleId: 'system',
        metadata: { cmd: 'rundll32.exe user32.dll,LockWorkStation' },
        triggers: ['execute'],
    },
    {
        id: 'sys:signout',
        name: 'Sign Out',
        icon: Icons.system,
        moduleId: 'system',
        metadata: { cmd: 'shutdown /l' },
        triggers: ['execute'],
    },
    {
        id: 'sys:devicemanager',
        name: 'Device Manager',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'devmgmt.msc' },
        triggers: ['execute'],
    },
    {
        id: 'sys:screenoff',
        name: 'Screen Off',
        icon: Icons.system,
        moduleId: 'system',
        metadata: { cmd: 'powershell -NoProfile -Command "(Add-Type \'[DllImport(\\\"user32.dll\\\")] public static extern int SendMessage(int h,int m,int w,int l);\' -Name a -Pas)::SendMessage(-1,0x0112,0xF170,2)"' },
        triggers: ['execute'],
    },
    {
        id: 'sys:networkconnections',
        name: 'Network Connections',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'ncpa.cpl' },
        triggers: ['execute'],
    },
    {
        id: 'sys:services',
        name: 'Services',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'services.msc' },
        triggers: ['execute'],
    },
    {
        id: 'sys:diskmanagement',
        name: 'Disk Management',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'diskmgmt.msc' },
        triggers: ['execute'],
    },
    {
        id: 'sys:eventviewer',
        name: 'Event Viewer',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'eventvwr.msc' },
        triggers: ['execute'],
    },
    {
        id: 'sys:regedit',
        name: 'Registry Editor',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'regedit' },
        triggers: ['execute'],
    },
    {
        id: 'sys:systemproperties',
        name: 'System Properties',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'sysdm.cpl' },
        triggers: ['execute'],
    },
    {
        id: 'sys:envvars',
        name: 'Environment Variables',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'rundll32 sysdm.cpl,EditEnvironmentVariables' },
        triggers: ['execute'],
    },
    {
        id: 'sys:startup',
        name: 'Startup Apps',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'explorer shell:startup' },
        triggers: ['execute'],
    },
    {
        id: 'sys:privacysecurity',
        name: 'Privacy & Security',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'start ms-settings:privacy' },
        triggers: ['execute'],
    },
    {
        id: 'sys:display',
        name: 'Display Settings',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'start ms-settings:display' },
        triggers: ['execute'],
    },
    {
        id: 'sys:bluetooth',
        name: 'Bluetooth Settings',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'start ms-settings:bluetooth' },
        triggers: ['execute'],
    },
    {
        id: 'sys:wifi',
        name: 'WiFi Settings',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'start ms-settings:network-wifi' },
        triggers: ['execute'],
    },
    {
        id: 'sys:personalization',
        name: 'Personalization',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'start ms-settings:personalization' },
        triggers: ['execute'],
    },
    {
        id: 'sys:colors',
        name: 'Colors & Accent',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'start ms-settings:colors' },
        triggers: ['execute'],
    },
    {
        id: 'sys:notifications',
        name: 'Notifications',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'start ms-settings:notifications' },
        triggers: ['execute'],
    },
    {
        id: 'sys:defaultapps',
        name: 'Default Apps',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'start ms-settings:defaultapps' },
        triggers: ['execute'],
    },
    {
        id: 'sys:powersleep',
        name: 'Power & Sleep',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'start ms-settings:powersleep' },
        triggers: ['execute'],
    },
    {
        id: 'sys:storage',
        name: 'Storage Settings',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'start ms-settings:storagesense' },
        triggers: ['execute'],
    },
    {
        id: 'sys:sound',
        name: 'Sound Settings',
        icon: Icons.settings,
        moduleId: 'system',
        metadata: { cmd: 'start ms-settings:sound' },
        triggers: ['execute'],
    },
]

export const systemProvider: Provider = {
    id: 'system',

    getRootItems: async () => SYSTEM_ACTIONS,

    onTrigger: async (item, trigger) => {
        if (trigger.type === 'execute') {
            const cmd = item.metadata.cmd as string
            exec(cmd)
            return { type: 'resetAndHide' }
        }
        return { type: 'noop' }
    },
}
